<?xml version="1.0" encoding="utf-8"?><Database Name="ShoesDB" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-K0H6TSU4;Initial Catalog=ShoesDB;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ShoesDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Shoe" Member="Shoes">
    <Type Name="Shoe">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ModelName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Size" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>